name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcups2-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Project + Dev Dependencies
        run: uv sync --extra dev --extra pycups

      - name: Build and Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force